version: '3.3'

services:

  hub:
    image: selenium/hub
    container_name: hub
    ports:
      - 4444:4444
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
    networks:
      - lambda_test

  chrome:
    image: selenium/node-chrome
    container_name: chrome
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 4
      NODE_MAX_INSTANCES: 4
    volumes:
      - lambda_test_data_chrome:/dev/shm
    ports:
      - 3001:5900
    links:
      - hub
    networks:
      - lambda_test

  firefox:
    image: selenium/node-firefox
    container_name: firefox
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
    volumes:
      - lambda_test_data_firefox:/dev/shm
    ports:
      - 3002:5900
    links:
      - hub
    networks:
      - lambda_test

  capture-service:
    container_name: capture-service
    image: capture-service
    depends_on:
      - hub
      - chrome
      - firefox
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - lambda_test_data:/usr/app/uploads
    ports:
      - 3000:3000
    links:
      - hub
      - chrome
      - firefox
    networks:
      - lambda_test

volumes:
  lambda_test_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
  
  lambda_test_data_chrome:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/chrome
      o: bind

  lambda_test_data_firefox:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/firefox
      o: bind

networks:
  lambda_test: 
    driver: bridge